[theme]
base = "dark"
primaryColor = "#e5484d"
backgroundColor = "#101319"
secondaryBackgroundColor = "#171a20"
textColor = "#fcfcfd"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
